### ISSUE TITLE
turn this into an awareness rising library for apps handling sensitive data

### ISSUE THREAD

**Issue by Giszmo** [twaddington/Android-Clipboard-Monitor#1]
By your readme.md I guess you are concerned about security implications of people copying sensitive stuff around. I'm tempted to use your code to add some clipboard security warning service to our Bitcoin wallet but maybe that is something much more general and could be encouraged to be integrated into all apps that suffer from careless users.

How about turning this library into an easily configurable library project that scans for stuff you shouldn't pass through the clipboard and alerts the user with a red screen if he does, optionally removing the data from the clipboard until the user clicks "it's safe. put it back there and go away"?

**Comment by drunckoder** [comment]
It's a good idea to warn people about safety but offering a bad protection - isn't. You can't be sure that your app is first to get clipboard data and remove it until another (malicious) app steals it. But users will think they are safe and they'll be even more mistaken.

**Comment by twaddington** [comment]
Thanks for the suggestion @Giszmo but I don't really have time to support the development of something like that at the moment.
