### ISSUE TITLE
Not Working in Android Oreo and Above 

### ISSUE THREAD

**Issue by rizwankhanMiranshah** [twaddington/Android-Clipboard-Monitor#4]
It work below then 8.1 but when i move to 8.1 the background services not working

**Comment by twaddington** [comment]
Yes, this project is unmaintained. It will need updating for more recent versions of Android.

**Comment by twaddington** [comment]
You would need to update the background service to be a "Foreground Service" with a persistent notification. Background services are no longer allowed in newer versions of Android.

https://developer.android.com/about/versions/oreo/android-8.0-changes
